

buildscript {
    ext {
        compose_version = '1.4.0'
        nav_version = "2.5.3"
        kotlin_version = "2.0.21"
        hilt_android = "2.57.2"
        build_gragle = "8.13.0"
    }

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$build_gragle"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.dagger:hilt-android-gradle-plugin:$hilt_android"
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.23.8"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
    }
}

plugins {
    id 'com.google.devtools.ksp' version '2.0.21-1.0.27' apply false
    id "org.jetbrains.kotlin.android" version "$kotlin_version" apply false
}